name: Deploy Site
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          lein: '2.9.4'
      - run: lein trampoline cljsbuild once min
      - uses: crazy-max/ghaction-github-pages@v2
        if: success()
        with:
          jekyll: false
          build_dir: resources/public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
